"""Generate the horizon × replan_every tuning sweep YAML.

Output: ``configs/tuning/horizon_replan_full.yaml`` — a 640-cell
sweep (2 maps × 4 agent_counts × 8 horizons × 10 seeds, ``method=ours``
only) used to identify the optimal ``(horizon, replan_every)``
configuration per (map, num_agents) before the main paper sweeps.

Design notes:

* ``replan_every`` is coupled to ``horizon`` at half its value
  (``replan_every = max(1, horizon // 2)``).  Coupling the two cuts
  the sweep axis from an 8×8 = 64-cell horizon×replan grid down to
  8 cells on the diagonal; the assumption (validated by §5.x
  preliminary data) is that the optimum sits near that diagonal.
* Map scale settings are map-specific.  Both maps
  (``random-64-64-10`` and ``warehouse-10-20-10-2-2``) sweep
  ``num_agents ∈ {25, 50, 75, 100}`` with ``num_humans = 50``.
  The larger ``warehouse-20-40-10-2-2`` map was dropped from this
  iteration to keep wall time bounded for the overnight launch.
* Group ordering is deterministic: random_H10..random_H80, then
  warehouse_small_H10..warehouse_small_H80.  Re-running this
  script on the same inputs produces a byte-identical YAML.

The harness's :func:`scripts.evaluation.run_paper_experiment.expand_manifest`
uses ``itertools.product`` over arbitrary sweep keys, so ``horizon``
and ``replan_every`` work without any harness extension.  The only
harness-side touch is one new entry in ``PAPER_SECTION_TO_STEPS``
named ``"horizon_replan_full_tuning"`` mapped to ``2000`` — added
in the same commit as the YAML.

Usage:

    python scripts/tuning/generate_horizon_yaml.py

To dry-run one cell after generation:

    .venv/bin/python scripts/evaluation/run_paper_experiment.py \\
        --config configs/tuning/horizon_replan_full.yaml \\
        --out /tmp/horizon_dryrun --workers 1 --limit 1
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, List

# Local-only import so we don't pollute ``scripts.tuning`` with a real
# package; the helper lives alongside this script.
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _sweep_config_common import (  # noqa: E402
    base_solver_budget_yaml,
    base_validity_guard_yaml,
    solver_provenance_comment,
)

# ---------------------------------------------------------------------------
# Sweep definition — single source of truth
# ---------------------------------------------------------------------------

SWEEP_VALUES: List[int] = [10, 20, 30, 40, 50, 60, 70, 80]
HORIZONS: List[int] = SWEEP_VALUES   # alias for clarity in the loop below
SEEDS: List[int] = list(range(10))

MAP_DEFS: List[Dict] = [
    {
        "tag": "random",
        "map_path": "data/maps/random-64-64-10.map",
        "agent_counts": [25, 50, 75, 100],
        "num_humans": 50,
    },
    {
        "tag": "warehouse_small",
        "map_path": "data/maps/warehouse-10-20-10-2-2.map",
        "agent_counts": [25, 50, 75, 100],
        "num_humans": 50,
    },
]


def _coupled_replan(horizon: int) -> int:
    """``replan_every = max(1, horizon // 2)``.

    The ``max(1, ...)`` floor is defensive — at the current
    SWEEP_VALUES floor of horizon=10 the formula yields 5 (well above
    1), but if a future caller shrinks the lowest horizon to 1 the
    formula must still produce a valid (non-zero) replan cadence.
    """
    return max(1, horizon // 2)

OUT_PATH = Path(__file__).resolve().parent.parent.parent \
    / "configs" / "tuning" / "horizon_replan_full.yaml"


# ---------------------------------------------------------------------------
# Generators (hand-written YAML; PyYAML reorders keys and emits flow-style
# inconsistently, so we keep formatting deterministic).
# ---------------------------------------------------------------------------


def _header() -> str:
    return (
        "# Auto-generated by scripts/tuning/generate_horizon_yaml.py.\n"
        "# DO NOT edit by hand; rerun the generator to regenerate.\n"
        "#\n"
        "# Horizon × replan_every tuning sweep.\n"
        "#\n"
        "#   2 maps × 4 agent_counts × 8 horizons × 10 seeds = 640 runs.\n"
        "#\n"
        "# replan_every is coupled to horizon at half its value\n"
        "# (replan_every = max(1, horizon // 2)), reducing the axis\n"
        "# from an 8×8 grid to the 8-cell diagonal.\n"
        "#\n"
        + solver_provenance_comment(["lacam_official"])
        + "\n"
        "name: horizon_replan_full_tuning\n"
        "description: |\n"
        "  Horizon × replan_every tuning sweep across 2 maps with\n"
        "  map-specific scale settings.\n"
        "  640 runs total: 2 maps × 4 agent_counts × 8 horizons ×\n"
        "  10 seeds. replan_every is coupled to horizon at half its value.\n"
        "  Goal: identify optimal (horizon, replan_every) per\n"
        "  (map, num_agents) for the main paper sweeps.\n"
        "\n"
        "base:\n"
        "  mode: lifelong\n"
        "  steps: 2000\n"
        "  human_model: random_walk\n"
        "  map_to_human_model:\n"
        "    warehouse-10-20-10-2-1: aisle\n"
        "    warehouse-10-20-10-2-2: aisle\n"
        "    random-64-64-10: random_walk\n"
        "  global_solver: lacam_official\n"
        "  local_planner: astar\n"
        "  task_allocator: congestion_avoidance\n"
        "  fov_radius: 4\n"
        "  safety_radius: 1\n"
        "  hard_safety: true\n"
        "  communication_mode: priority\n"
        + base_solver_budget_yaml()
        + base_validity_guard_yaml()
        +         "  log_violations_timeline: false\n"
        "\n"
        "seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n"
        "\n"
        "groups:\n"
    )


def _group_yaml(map_def: Dict, horizon: int) -> str:
    """Emit a single sweep group in deterministic key order."""
    replan = _coupled_replan(horizon)
    agent_counts_inline = "[" + ", ".join(str(n) for n in map_def["agent_counts"]) + "]"
    return (
        f"  # ----- {map_def['tag']} H={horizon} (replan_every={replan}) -----\n"
        f"  - name: {map_def['tag']}_H{horizon}\n"
        f"    sweep:\n"
        f"      method:       [ours]\n"
        f"      map_path:     [{map_def['map_path']}]\n"
        f"      num_agents:   {agent_counts_inline}\n"
        f"      num_humans:   [{map_def['num_humans']}]\n"
        f"      horizon:      [{horizon}]\n"
        f"      replan_every: [{replan}]\n"
    )


def build_yaml() -> str:
    parts = [_header()]
    for map_def in MAP_DEFS:
        for h in HORIZONS:
            parts.append(_group_yaml(map_def, h))
    return "".join(parts)


# ---------------------------------------------------------------------------
# Verification — re-parse the emitted YAML and compute the cell count
# ---------------------------------------------------------------------------


def verify(yaml_text: str) -> int:
    import yaml
    spec = yaml.safe_load(yaml_text)
    seeds = spec.get("seeds", [])
    total = 0
    for group in spec.get("groups", []):
        sweep = group.get("sweep", {})
        cells = 1
        for axis in ("method", "map_path", "num_agents", "num_humans",
                     "horizon", "replan_every"):
            cells *= len(sweep[axis])
        total += cells * len(seeds)
    return total


def main() -> None:
    yaml_text = build_yaml()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(yaml_text)
    print(f"wrote {OUT_PATH} ({len(yaml_text):,} bytes)")
    total = verify(yaml_text)
    print(f"cell count (re-parsed): {total}")
    expected = (
        len(MAP_DEFS)
        * len(MAP_DEFS[0]["agent_counts"])
        * len(HORIZONS)
        * len(SEEDS)
    )
    print(f"expected:               {expected}")
    if total != expected:
        raise SystemExit(f"FAIL: cell count {total} != {expected}")
    print("OK")


if __name__ == "__main__":
    main()
