"""DEPRECATED — superseded by the four-sweep split.

  scripts/tuning/generate_scaling_agents_fov3_safe1_yaml.py
  scripts/tuning/generate_scaling_agents_fov4_safe2_yaml.py
  scripts/tuning/generate_scaling_humans_fov3_safe1_yaml.py
  scripts/tuning/generate_scaling_humans_fov4_safe2_yaml.py

See ``scripts/tuning/generate_scaling_agents_yaml.py`` (also deprecated)
for the rationale.  Kept on disk for audit-trail visibility.

----------------------------------------------------------------------

Generate the §5.4 exogenous-density scaling sweep YAML.

Output: ``configs/tuning/scaling_humans.yaml`` — an 840-cell sweep
(6 solvers × 2 maps × 7 num_humans × 10 seeds) sweeping
``num_humans`` at fixed (num_agents, fov, safe, horizon).

Companion to ``generate_scaling_agents_yaml.py``.  The two sweeps
together form the §5.4 controlled-density matrix:

  * scaling_agents:  num_agents varies in {25..250},  num_humans = 100
  * scaling_humans:  num_humans varies in {25..250},  num_agents = 200

Hypothesis under test (§5.4):
    POE-Solver's safety properties (Theorem 1) and throughput
    behavior generalize across Tier-1 MAPF backends and across
    the exogenous-density axis.

Design notes:

* Single method (``ours``); ``global_solver`` axis varies the
  Tier-1 backend.  Tier-2 (buffer-aware controller) held constant.
* ``num_agents`` is fixed at 200 to hold the controlled-agent
  density constant while exogenous density varies.
* ``horizon=40`` and ``replan_every=20`` come from horizon
  tuning (same as scaling_agents).
* ``fov_radius`` and ``safety_radius`` are PLACEHOLDERS until the
  fov/safety sweep analysis completes.
* Group naming: ``<solver>_<map_tag>`` (12 groups; each group's
  inner sweep is the ``num_humans`` axis).

TODO — UPDATE BEFORE LAUNCH
---------------------------

``PLACEHOLDER_FOV`` and ``PLACEHOLDER_SAFE`` must be set from the
fov/safety sweep analysis before launching this sweep.  Workflow
mirrors scaling_agents: pick the (r_fov, r_safe) pair that
maximizes throughput at the §5.4 reference scale subject to
``agent_attr == 0``, edit these two lines, regenerate, launch.

Usage
-----

    python scripts/tuning/generate_scaling_humans_yaml.py

Reproducibility: re-running with identical constants produces a
byte-identical YAML.
"""
from __future__ import annotations

from pathlib import Path
from typing import List

# Local-only import so we don't pollute ``scripts.tuning`` with a real
# package; the helper lives alongside this script.
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _sweep_config_common import (  # noqa: E402
    base_solver_budget_yaml,
    base_validity_guard_yaml,
    solver_provenance_comment,
)

# ---------------------------------------------------------------------------
# PLACEHOLDER values — UPDATE FROM FOV/SAFETY ANALYSIS BEFORE LAUNCH.
# ---------------------------------------------------------------------------

PLACEHOLDER_FOV: int = 4    # TODO: set from fov/safety sweep analysis
PLACEHOLDER_SAFE: int = 1   # TODO: set from fov/safety sweep analysis

# ---------------------------------------------------------------------------
# Sweep definition — single source of truth
# ---------------------------------------------------------------------------

SOLVERS: List[str] = [
    "cbsh2",
    "lacam_official",
    "lacam3",
    "lns2",
    "pbs",
    "pibt2",
]

MAPS: List[str] = [
    "data/maps/warehouse-10-20-10-2-2.map",
    "data/maps/random-64-64-10.map",
]

HUMAN_COUNTS: List[int] = [25, 50, 75, 100, 150, 200, 250]

NUM_AGENTS: int = 200        # fixed (controlled-agent density)
HORIZON: int = 40            # fixed from horizon tuning
REPLAN_EVERY: int = 20       # fixed, paired with H/2

SEEDS: List[int] = list(range(10))

OUT_PATH = Path(__file__).resolve().parent.parent.parent \
    / "configs" / "tuning" / "scaling_humans.yaml"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _map_tag(map_path: str) -> str:
    """Derive a YAML-safe tag from a map path."""
    stem = Path(map_path).stem
    return stem.replace("-", "_")


# ---------------------------------------------------------------------------
# YAML emission — hand-written for deterministic formatting
# ---------------------------------------------------------------------------


def _header() -> str:
    return (
        "# Auto-generated by scripts/tuning/generate_scaling_humans_yaml.py.\n"
        "# DO NOT edit by hand; rerun the generator to regenerate.\n"
        "#\n"
        "# §5.4 exogenous-density scaling sweep.\n"
        "#\n"
        "#   6 solvers × 2 maps × 7 num_humans × 10 seeds = 840 runs.\n"
        "#\n"
        "# Single method (`ours`); the Tier-1 solver is varied across\n"
        "# {cbsh2, lacam_official, lacam3, lns2, pbs, pibt2} to test\n"
        "# whether POE-Solver's safety + throughput properties hold\n"
        "# across Tier-1 backends as exogenous density grows.\n"
        "# num_agents is fixed at 200; horizon=40, replan_every=20\n"
        "# come from horizon tuning.\n"
        "#\n"
        "# Companion to scaling_agents.yaml — together the two sweeps\n"
        "# form the §5.4 controlled-density matrix.\n"
        "#\n"
        "# TODO — UPDATE BEFORE LAUNCH.\n"
        "# fov_radius and safety_radius below are PLACEHOLDERS pending\n"
        "# the fov/safety sweep analysis.  Update PLACEHOLDER_FOV /\n"
        "# PLACEHOLDER_SAFE in the generator and regenerate.\n"
        "#\n"
        + solver_provenance_comment(SOLVERS)
        + "\n"
        "name: scaling_humans\n"
        "description: |\n"
        "  §5.4 exogenous-density scaling sweep across 6 Tier-1 solvers\n"
        "  and 2 maps.  840 runs total: 6 solvers × 2 maps × 7 num_humans\n"
        "  × 10 seeds.  num_agents fixed at 200.  fov/safety values are\n"
        "  PROVISIONAL pending the fov/safety sweep analysis.\n"
        "\n"
        "base:\n"
        "  mode: lifelong\n"
        "  steps: 2000\n"
        "  human_model: random_walk\n"
        "  map_to_human_model:\n"
        "    warehouse-10-20-10-2-1: aisle\n"
        "    warehouse-10-20-10-2-2: aisle\n"
        "    random-64-64-10: random_walk\n"
        "  local_planner: astar\n"
        "  task_allocator: congestion_avoidance\n"
        "  hard_safety: true\n"
        "  communication_mode: priority\n"
        + base_solver_budget_yaml()
        +         "  log_violations_timeline: true\n"
        "\n"
        + base_validity_guard_yaml()
        + "\n"
        "seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n"
        "\n"
        "groups:\n"
    )


def _group_yaml(solver: str, map_path: str) -> str:
    """Emit a single sweep group for one (solver, map) combination.
    The group's inner sweep varies ``num_humans`` over ``HUMAN_COUNTS``."""
    map_tag = _map_tag(map_path)
    human_counts_inline = "[" + ", ".join(str(n) for n in HUMAN_COUNTS) + "]"
    return (
        f"  # ----- {solver} on {map_tag} -----\n"
        f"  - name: {solver}_{map_tag}\n"
        f"    sweep:\n"
        f"      method:        [ours]\n"
        f"      global_solver: [{solver}]\n"
        f"      map_path:      [{map_path}]\n"
        f"      num_agents:    [{NUM_AGENTS}]\n"
        f"      num_humans:    {human_counts_inline}\n"
        f"      horizon:       [{HORIZON}]\n"
        f"      replan_every:  [{REPLAN_EVERY}]\n"
        f"      fov_radius:    [{PLACEHOLDER_FOV}]\n"
        f"      safety_radius: [{PLACEHOLDER_SAFE}]\n"
    )


def build_yaml() -> str:
    parts = [_header()]
    for solver in SOLVERS:
        for map_path in MAPS:
            parts.append(_group_yaml(solver, map_path))
    return "".join(parts)


# ---------------------------------------------------------------------------
# Verification — re-parse the emitted YAML and compute the cell count
# ---------------------------------------------------------------------------


def verify(yaml_text: str) -> int:
    import yaml
    spec = yaml.safe_load(yaml_text)
    seeds = spec.get("seeds", [])
    total = 0
    for group in spec.get("groups", []):
        sweep = group.get("sweep", {})
        cells = 1
        for axis in ("method", "global_solver", "map_path", "num_agents",
                     "num_humans", "horizon", "replan_every",
                     "fov_radius", "safety_radius"):
            cells *= len(sweep[axis])
        total += cells * len(seeds)
    return total


def main() -> None:
    yaml_text = build_yaml()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(yaml_text)
    print(f"wrote {OUT_PATH} ({len(yaml_text):,} bytes)")

    expected = (
        len(SOLVERS) * len(MAPS) * len(HUMAN_COUNTS) * len(SEEDS)
    )
    total = verify(yaml_text)
    print(f"groups: {len(SOLVERS) * len(MAPS)}")
    print(f"cell count (re-parsed): {total}")
    print(f"expected:               {expected}")
    if total != expected:
        raise SystemExit(f"FAIL: cell count {total} != {expected}")
    print("OK")


if __name__ == "__main__":
    main()
