"""Generate the §3 hard-vs-soft safety ablation sweep YAML.

Output: ``configs/tuning/soft_safety_ablation.yaml`` — a 180-cell
sweep on warehouse-10-20-10-2-2 that varies ``hard_safety`` over
{true, false} at fixed exogenous density (X=100) and the standard
§5.6 operating point.

Hypothesis under test (§3):
    The hard-safety guarantee (Theorem 1: agent_attr=0) and the
    soft-safety mode (BLOCKED_CELL_COST=50 penalty instead of
    impassable buffer cells) trade off cleanly:
      * hard mode: agent_attr=0 always; throughput may collapse
        under high contention (agents safety-wait).
      * soft mode: agent_attr>0 admitted on forced encroachments;
        throughput preserved at the cost of safety guarantees.

Design notes:

* Single method (``ours``); only POE-Solver supports the hard/soft
  knob (pibt2_fr and lacam_blind use ``controller_kind=global_only``
  which is rigid regardless).
* ``hard_safety`` is the ablation axis, swept over {true, false}.
* All other hyperparameters match the §5.6 sweep (horizon=40,
  replan=20, fov=4, safe=1, task_allocator=congestion_avoidance,
  lambda_conflict=0.5, max_rounds=5).
* ``BLOCKED_CELL_COST`` stays at its hardcoded value of 50
  (``local_planner.py:38``).  The paper fixes cost_soft=50 and
  does not promise a cost sweep; no SimConfig field is added.
* Two sweep groups, one per hard_safety value, so the grouping is
  self-documenting per arm.

Cell count:
    2 hard_safety values × 9 num_agents × 10 seeds = 180.

Usage::

    python scripts/tuning/generate_soft_safety_ablation_yaml.py

Reproducibility: identical constants → byte-identical YAML.
"""
from __future__ import annotations

from pathlib import Path
from typing import List

# Local-only import so we don't pollute ``scripts.tuning`` with a real
# package; the helper lives alongside this script.
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _sweep_config_common import (  # noqa: E402
    base_solver_budget_yaml,
    base_validity_guard_yaml,
    solver_provenance_comment,
)

# ---------------------------------------------------------------------------
# Sweep constants — single source of truth.
# ---------------------------------------------------------------------------

HARD_SAFETY_VALUES: List[bool] = [True, False]

M_VALUES: List[int] = [50, 100, 150, 200, 250, 300, 350, 400, 450]
NUM_HUMANS: int = 100

MAP_PATH: str = "data/maps/warehouse-10-20-10-2-2.map"

HORIZON: int = 40
REPLAN_EVERY: int = 20
FOV_RADIUS: int = 4
SAFETY_RADIUS: int = 1
GLOBAL_SOLVER: str = "lacam_official"

SEEDS: List[int] = list(range(10))

OUT_PATH = Path(__file__).resolve().parent.parent.parent \
    / "configs" / "tuning" / "soft_safety_ablation.yaml"


def _arm_tag(hard: bool) -> str:
    return "hard" if hard else "soft"


def _header() -> str:
    return (
        "# Auto-generated by scripts/tuning/generate_soft_safety_ablation_yaml.py.\n"
        "# DO NOT edit by hand; rerun the generator to regenerate.\n"
        "#\n"
        "# §3 hard-vs-soft safety ablation.\n"
        "#\n"
        "#   2 hard_safety values × 9 num_agents × 10 seeds = 180 runs.\n"
        "#\n"
        "# Method: ours only (only POE-Solver supports the hard/soft\n"
        "# knob; rigid-follower baselines bypass the relevant code path).\n"
        "# Map: warehouse-10-20-10-2-2.  num_humans fixed at 100.\n"
        "# Operating point matches §5.6: horizon=40, replan=20, fov=4,\n"
        "# safe=1, task_allocator=congestion_avoidance.\n"
        "# cost_soft stays at its hardcoded 50 (local_planner.py:38).\n"
        "#\n"
        + solver_provenance_comment([GLOBAL_SOLVER])
        + "\n"
        "name: soft_safety_ablation\n"
        "description: |\n"
        "  §3 hard-vs-soft safety ablation on warehouse-10-20-10-2-2.\n"
        "  180 cells = 2 hard_safety values × 9 num_agents × 10 seeds.\n"
        "  Expected contrast: hard preserves Theorem 1 (agent_attr=0)\n"
        "  but throughput collapses at high M; soft trades agent_attr\n"
        "  for throughput.\n"
        "\n"
        "base:\n"
        "  mode: lifelong\n"
        "  steps: 2000\n"
        "  human_model: random_walk\n"
        "  map_to_human_model:\n"
        "    warehouse-10-20-10-2-1: aisle\n"
        "    warehouse-10-20-10-2-2: aisle\n"
        "    random-64-64-10: random_walk\n"
        f"  global_solver: {GLOBAL_SOLVER}\n"
        f"  horizon: {HORIZON}\n"
        f"  replan_every: {REPLAN_EVERY}\n"
        f"  fov_radius: {FOV_RADIUS}\n"
        f"  safety_radius: {SAFETY_RADIUS}\n"
        "  communication_mode: priority\n"
        "  local_planner: astar\n"
        "  task_allocator: congestion_avoidance\n"
        "  lambda_conflict: 0.5\n"
        "  max_rounds: 5\n"
        + base_solver_budget_yaml()
        + base_validity_guard_yaml()
        +         "  log_violations_timeline: true\n"
        "\n"
        "seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n"
        "\n"
        "groups:\n"
    )


def _group_yaml(hard: bool) -> str:
    arm = _arm_tag(hard)
    m_inline = "[" + ", ".join(str(n) for n in M_VALUES) + "]"
    return (
        f"  # ----- ours @ {arm}_safety on warehouse-10-20-10-2-2 -----\n"
        f"  - name: ours_{arm}_safety\n"
        f"    sweep:\n"
        f"      method:      [ours]\n"
        f"      map_path:    [{MAP_PATH}]\n"
        f"      num_agents:  {m_inline}\n"
        f"      num_humans:  [{NUM_HUMANS}]\n"
        f"      hard_safety: [{str(hard).lower()}]\n"
    )


def build_yaml() -> str:
    parts = [_header()]
    for hard in HARD_SAFETY_VALUES:
        parts.append(_group_yaml(hard))
    return "".join(parts)


def verify(yaml_text: str) -> int:
    import yaml
    spec = yaml.safe_load(yaml_text)
    total = 0
    for g in spec["groups"]:
        cells = 1
        for v in g["sweep"].values():
            cells *= len(v)
        total += cells * len(spec["seeds"])
    return total


def main() -> None:
    yaml_text = build_yaml()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(yaml_text)
    print(f"wrote {OUT_PATH} ({len(yaml_text):,} bytes)")
    expected = len(HARD_SAFETY_VALUES) * len(M_VALUES) * len(SEEDS)
    total = verify(yaml_text)
    print(f"groups: {len(HARD_SAFETY_VALUES)}")
    print(f"cell count (re-parsed): {total}")
    print(f"expected:               {expected}")
    if total != expected:
        raise SystemExit(f"FAIL: cell count {total} != {expected}")
    print("OK")


if __name__ == "__main__":
    main()
