"""Generate the FOV × safety_radius sensitivity sweep YAML.

Output: ``configs/tuning/fov_safety_sweep.yaml`` — a 700-cell
sweep (35 valid (fov, safe) pairs × 2 maps × 10 seeds, ``method=ours``
only) used to characterize §5.3 sensitivity of safety metrics to
the observable-region radius and the buffer radius.

Constraint
----------

``r_fov > r_safe`` (strict).  An agent cannot enforce a buffer of
radius ``r_safe`` around exogenous agents it cannot observe; the
buffer-aware controller's inflated forbidden region F is restricted
to ``X_t^{Phi_i}`` (humans in the FOV).  We therefore prune pairs
with ``r_fov ≤ r_safe`` from the sweep.

Valid pairs per map:

  fov=2  → safe ∈ {1}              = 1
  fov=3  → safe ∈ {1,2}            = 2
  fov=4  → safe ∈ {1,2,3}          = 3
  fov=5  → safe ∈ {1,2,3,4}        = 4
  fov=6,7,8,9,10 → safe ∈ {1..5}   = 5 × 5 = 25
  ------------------------------------------
  total                            = 35

  35 pairs × 2 maps × 10 seeds = 700 runs.

TODO (post-horizon-tuning)
--------------------------

The per-map ``(num_agents, num_humans, horizon, replan_every)``
values in ``REFERENCE_SCALE`` are PLACEHOLDERS pending the horizon
tuning sweep (see ``logs/tuning/horizon_replan_full/``).  Once that
sweep completes, update each entry to the best-throughput row for
``(map, num_agents)`` per the tuning analysis, then re-run this
generator.

Usage
-----

    python scripts/tuning/generate_fov_safety_yaml.py

Reproducibility: re-running with identical ``FOV_VALUES`` /
``SAFETY_VALUES`` / ``MAPS`` / ``REFERENCE_SCALE`` / ``SEEDS``
produces a byte-identical YAML.
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, List

# Local-only import so we don't pollute ``scripts.tuning`` with a real
# package; the helper lives alongside this script.
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _sweep_config_common import (  # noqa: E402
    base_solver_budget_yaml,
    base_validity_guard_yaml,
    solver_provenance_comment,
)

# ---------------------------------------------------------------------------
# Sweep definition — single source of truth
# ---------------------------------------------------------------------------

FOV_VALUES: List[int] = [2, 3, 4, 5, 6, 7, 8, 9, 10]
SAFETY_VALUES: List[int] = [1, 2, 3, 4, 5]
SEEDS: List[int] = list(range(10))

MAPS: List[str] = [
    "data/maps/warehouse-10-20-10-2-2.map",
    "data/maps/random-64-64-10.map",
]

# PLACEHOLDER values — update after horizon tuning analysis completes.
# One entry per map; keys match the map_path values in ``MAPS`` above.
# Each entry is the (num_agents, num_humans, horizon, replan_every)
# at which fov/safety sensitivity will be measured.
REFERENCE_SCALE: Dict[str, Dict[str, int]] = {
    "data/maps/warehouse-10-20-10-2-2.map": {
        "num_agents":   100,
        "num_humans":   50,
        "horizon":      40,
        "replan_every": 20,
    },
    "data/maps/random-64-64-10.map": {
        "num_agents":   100,
        "num_humans":   50,
        "horizon":      40,
        "replan_every": 20,
    },
}

OUT_PATH = Path(__file__).resolve().parent.parent.parent \
    / "configs" / "tuning" / "fov_safety_sweep.yaml"


# ---------------------------------------------------------------------------
# Constraint helper
# ---------------------------------------------------------------------------


def valid_pairs() -> List[tuple]:
    """All ``(fov, safe)`` pairs satisfying ``r_fov > r_safe``.

    Ordering is deterministic: outer loop over FOV_VALUES (ascending),
    inner loop over SAFETY_VALUES (ascending).  This gives the group
    ordering called out in the spec:
        fov2_safe1, fov3_safe1, fov3_safe2, fov4_safe1, …
    """
    pairs = []
    for fov in FOV_VALUES:
        for safe in SAFETY_VALUES:
            if fov > safe:
                pairs.append((fov, safe))
    return pairs


def _map_tag(map_path: str) -> str:
    """Derive a YAML-safe group tag from a map path.

    ``data/maps/warehouse-10-20-10-2-1.map`` → ``warehouse_10_20_10_2_1``
    ``data/maps/random-64-64-10.map``        → ``random_64_64_10``
    """
    stem = Path(map_path).stem
    return stem.replace("-", "_")


# ---------------------------------------------------------------------------
# YAML emission — hand-written for deterministic formatting
# ---------------------------------------------------------------------------


def _header() -> str:
    return (
        "# Auto-generated by scripts/tuning/generate_fov_safety_yaml.py.\n"
        "# DO NOT edit by hand; rerun the generator to regenerate.\n"
        "#\n"
        "# FOV × safety_radius sensitivity sweep (paper §5.3).\n"
        "#\n"
        "#   35 valid (fov, safe) pairs × 2 maps × 10 seeds = 700 runs.\n"
        "#\n"
        "# Constraint: r_fov > r_safe (strict — agent cannot enforce a\n"
        "# safety buffer on cells outside its observable region).\n"
        "#\n"
        "# TODO — UPDATE REFERENCE SCALE AFTER HORIZON TUNING.\n"
        "# The per-map (num_agents, num_humans, horizon, replan_every)\n"
        "# values below are PLACEHOLDERS pending the horizon tuning sweep\n"
        "# (logs/tuning/horizon_replan_full/).  Once that sweep completes,\n"
        "# update REFERENCE_SCALE in the generator and regenerate.\n"
        "#\n"
        + solver_provenance_comment(["lacam_official"])
        + "\n"
        "name: fov_safety_sweep\n"
        "description: |\n"
        "  §5.3 FOV × safety_radius sensitivity sweep across 2 maps.\n"
        "  700 runs total: 35 valid (fov, safe) pairs × 2 maps × 10 seeds.\n"
        "  Constraint: r_fov > r_safe (strict).\n"
        "  Reference scale (num_agents/horizon/replan_every) is\n"
        "  PROVISIONAL pending the horizon tuning analysis.\n"
        "\n"
        "base:\n"
        "  mode: lifelong\n"
        "  steps: 2000\n"
        "  human_model: random_walk\n"
        "  map_to_human_model:\n"
        "    warehouse-10-20-10-2-1: aisle\n"
        "    warehouse-10-20-10-2-2: aisle\n"
        "    random-64-64-10: random_walk\n"
        "  global_solver: lacam_official\n"
        "  local_planner: astar\n"
        "  task_allocator: congestion_avoidance\n"
        "  hard_safety: true\n"
        "  communication_mode: priority\n"
        + base_solver_budget_yaml()
        + base_validity_guard_yaml()
        +         "  log_violations_timeline: true\n"
        "\n"
        "seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n"
        "\n"
        "groups:\n"
    )


def _group_yaml(map_path: str, fov: int, safe: int) -> str:
    """Emit a single sweep group in deterministic key order."""
    scale = REFERENCE_SCALE[map_path]
    tag = _map_tag(map_path)
    return (
        f"  # ----- {tag} fov={fov} safe={safe} -----\n"
        f"  - name: {tag}_fov{fov}_safe{safe}\n"
        f"    sweep:\n"
        f"      method:       [ours]\n"
        f"      map_path:     [{map_path}]\n"
        f"      num_agents:   [{scale['num_agents']}]\n"
        f"      num_humans:   [{scale['num_humans']}]\n"
        f"      horizon:      [{scale['horizon']}]\n"
        f"      replan_every: [{scale['replan_every']}]\n"
        f"      fov_radius:   [{fov}]\n"
        f"      safety_radius: [{safe}]\n"
    )


def build_yaml() -> str:
    parts = [_header()]
    pairs = valid_pairs()
    # Outer loop: maps in declaration order.
    # Inner loop: (fov, safe) pairs in (fov ascending, safe ascending) order.
    for map_path in MAPS:
        for fov, safe in pairs:
            parts.append(_group_yaml(map_path, fov, safe))
    return "".join(parts)


# ---------------------------------------------------------------------------
# Verification — re-parse the emitted YAML and compute the cell count
# ---------------------------------------------------------------------------


def verify(yaml_text: str) -> int:
    import yaml
    spec = yaml.safe_load(yaml_text)
    seeds = spec.get("seeds", [])
    total = 0
    for group in spec.get("groups", []):
        sweep = group.get("sweep", {})
        cells = 1
        for axis in ("method", "map_path", "num_agents", "num_humans",
                     "horizon", "replan_every", "fov_radius",
                     "safety_radius"):
            cells *= len(sweep[axis])
        total += cells * len(seeds)
    return total


def main() -> None:
    yaml_text = build_yaml()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(yaml_text)
    print(f"wrote {OUT_PATH} ({len(yaml_text):,} bytes)")

    pairs = valid_pairs()
    print(f"valid (fov, safe) pairs per map: {len(pairs)}")
    expected = len(pairs) * len(MAPS) * len(SEEDS)
    total = verify(yaml_text)
    print(f"cell count (re-parsed): {total}")
    print(f"expected:               {expected}")
    if total != expected:
        raise SystemExit(f"FAIL: cell count {total} != {expected}")
    print("OK")


if __name__ == "__main__":
    main()
