"""DEPRECATED — superseded by the four-sweep split.

  scripts/tuning/generate_scaling_agents_fov3_safe1_yaml.py
  scripts/tuning/generate_scaling_agents_fov4_safe2_yaml.py
  scripts/tuning/generate_scaling_humans_fov3_safe1_yaml.py
  scripts/tuning/generate_scaling_humans_fov4_safe2_yaml.py

The split removes the 6→4 solver winnowing (cbsh2 / pbs dropped after the
§5.5 / horizon-tuning analysis showed them dominated), hardcodes the two
fov/safe operating points instead of using PLACEHOLDER constants, and
splits the (M-or-X axis) × (fov/safe) matrix into four independent files
so two clusters can each run two sweeps sequentially with no run-time
decisions.

Kept on disk for audit-trail visibility; safe to ignore for new work.

----------------------------------------------------------------------

Generate the §5.4 controlled-agent scaling sweep YAML.

Output: ``configs/tuning/scaling_agents.yaml`` — an 840-cell sweep
(6 solvers × 2 maps × 7 agent counts × 10 seeds) sweeping
``num_agents`` at fixed (fov, safe, horizon, num_humans).

Hypothesis under test (§5.4):
    POE-Solver's safety properties (Theorem 1) and throughput
    behavior generalize across Tier-1 MAPF backends and across
    the agent-density scaling axis.

Design notes:

* Single method (``ours``); the Tier-1 solver is varied via the
  ``global_solver`` axis.  This keeps Tier-2 (buffer-aware
  controller) constant; only the global planner changes.
* ``num_humans`` is fixed at 100 to hold the exogenous-agent
  density constant while agent density varies.
* ``horizon`` and ``replan_every`` are fixed at the values
  identified by the horizon tuning sweep (H=40, R=20).
* ``fov_radius`` and ``safety_radius`` are PLACEHOLDERS until the
  fov/safety sweep analysis completes — see TODO below.
* Group naming: ``<solver>_<map_tag>`` (12 groups; each group's
  inner sweep is the ``num_agents`` axis).
* Order: solvers in spec order × maps in spec order.

TODO — UPDATE BEFORE LAUNCH
---------------------------

``PLACEHOLDER_FOV`` and ``PLACEHOLDER_SAFE`` must be set from the
fov/safety sweep analysis before launching this sweep.  After the
fov/safety sweep completes, pick the (r_fov, r_safe) pair that
maximizes throughput at the §5.4 reference scale (warehouse,
M=100 or M=150) subject to ``agent_attr == 0`` (Theorem 1 must
hold).  Edit these two lines at the top of this script and
re-run the generator.

Usage
-----

    python scripts/tuning/generate_scaling_agents_yaml.py

Reproducibility: re-running with identical constants produces a
byte-identical YAML.
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, List

# Local-only import so we don't pollute ``scripts.tuning`` with a real
# package; the helper lives alongside this script.
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _sweep_config_common import (  # noqa: E402
    base_solver_budget_yaml,
    base_validity_guard_yaml,
    solver_provenance_comment,
)

# ---------------------------------------------------------------------------
# PLACEHOLDER values — UPDATE FROM FOV/SAFETY ANALYSIS BEFORE LAUNCH.
# ---------------------------------------------------------------------------

PLACEHOLDER_FOV: int = 4    # TODO: set from fov/safety sweep analysis
PLACEHOLDER_SAFE: int = 1   # TODO: set from fov/safety sweep analysis

# ---------------------------------------------------------------------------
# Sweep definition — single source of truth
# ---------------------------------------------------------------------------

SOLVERS: List[str] = [
    "cbsh2",
    "lacam_official",
    "lacam3",
    "lns2",
    "pbs",
    "pibt2",
]

MAPS: List[str] = [
    "data/maps/warehouse-10-20-10-2-2.map",
    "data/maps/random-64-64-10.map",
]

AGENT_COUNTS: List[int] = [25, 50, 75, 100, 150, 200, 250]

NUM_HUMANS: int = 100        # fixed
HORIZON: int = 40            # fixed from horizon tuning
REPLAN_EVERY: int = 20       # fixed, paired with H/2

SEEDS: List[int] = list(range(10))

OUT_PATH = Path(__file__).resolve().parent.parent.parent \
    / "configs" / "tuning" / "scaling_agents.yaml"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _map_tag(map_path: str) -> str:
    """Derive a YAML-safe tag from a map path.

    ``data/maps/warehouse-10-20-10-2-2.map`` → ``warehouse_10_20_10_2_2``
    ``data/maps/random-64-64-10.map``        → ``random_64_64_10``
    """
    stem = Path(map_path).stem
    return stem.replace("-", "_")


# ---------------------------------------------------------------------------
# YAML emission — hand-written for deterministic formatting
# ---------------------------------------------------------------------------


def _header() -> str:
    return (
        "# Auto-generated by scripts/tuning/generate_scaling_agents_yaml.py.\n"
        "# DO NOT edit by hand; rerun the generator to regenerate.\n"
        "#\n"
        "# §5.4 controlled-agent scaling sweep.\n"
        "#\n"
        "#   6 solvers × 2 maps × 7 num_agents × 10 seeds = 840 runs.\n"
        "#\n"
        "# Single method (`ours`); the Tier-1 solver is varied across\n"
        "# {cbsh2, lacam_official, lacam3, lns2, pbs, pibt2} to test\n"
        "# whether POE-Solver's safety + throughput properties hold\n"
        "# across Tier-1 backends.  num_humans is fixed at 100;\n"
        "# horizon=40, replan_every=20 come from horizon tuning.\n"
        "#\n"
        "# TODO — UPDATE BEFORE LAUNCH.\n"
        "# fov_radius and safety_radius below are PLACEHOLDERS pending\n"
        "# the fov/safety sweep analysis.  Update PLACEHOLDER_FOV /\n"
        "# PLACEHOLDER_SAFE in the generator and regenerate.\n"
        "#\n"
        + solver_provenance_comment(SOLVERS)
        + "\n"
        "name: scaling_agents\n"
        "description: |\n"
        "  §5.4 controlled-agent scaling sweep across 6 Tier-1 solvers\n"
        "  and 2 maps.  840 runs total: 6 solvers × 2 maps × 7 num_agents\n"
        "  × 10 seeds.  num_humans fixed at 100.  fov/safety values are\n"
        "  PROVISIONAL pending the fov/safety sweep analysis.\n"
        "\n"
        "base:\n"
        "  mode: lifelong\n"
        "  steps: 2000\n"
        "  human_model: random_walk\n"
        "  map_to_human_model:\n"
        "    warehouse-10-20-10-2-1: aisle\n"
        "    warehouse-10-20-10-2-2: aisle\n"
        "    random-64-64-10: random_walk\n"
        "  local_planner: astar\n"
        "  task_allocator: congestion_avoidance\n"
        "  hard_safety: true\n"
        "  communication_mode: priority\n"
        + base_solver_budget_yaml()
        +         "  log_violations_timeline: true\n"
        "\n"
        + base_validity_guard_yaml()
        + "\n"
        "seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n"
        "\n"
        "groups:\n"
    )


def _group_yaml(solver: str, map_path: str) -> str:
    """Emit a single sweep group for one (solver, map) combination.
    The group's inner sweep varies ``num_agents`` over ``AGENT_COUNTS``."""
    map_tag = _map_tag(map_path)
    agent_counts_inline = "[" + ", ".join(str(n) for n in AGENT_COUNTS) + "]"
    return (
        f"  # ----- {solver} on {map_tag} -----\n"
        f"  - name: {solver}_{map_tag}\n"
        f"    sweep:\n"
        f"      method:        [ours]\n"
        f"      global_solver: [{solver}]\n"
        f"      map_path:      [{map_path}]\n"
        f"      num_agents:    {agent_counts_inline}\n"
        f"      num_humans:    [{NUM_HUMANS}]\n"
        f"      horizon:       [{HORIZON}]\n"
        f"      replan_every:  [{REPLAN_EVERY}]\n"
        f"      fov_radius:    [{PLACEHOLDER_FOV}]\n"
        f"      safety_radius: [{PLACEHOLDER_SAFE}]\n"
    )


def build_yaml() -> str:
    parts = [_header()]
    for solver in SOLVERS:
        for map_path in MAPS:
            parts.append(_group_yaml(solver, map_path))
    return "".join(parts)


# ---------------------------------------------------------------------------
# Verification — re-parse the emitted YAML and compute the cell count
# ---------------------------------------------------------------------------


def verify(yaml_text: str) -> int:
    import yaml
    spec = yaml.safe_load(yaml_text)
    seeds = spec.get("seeds", [])
    total = 0
    for group in spec.get("groups", []):
        sweep = group.get("sweep", {})
        cells = 1
        for axis in ("method", "global_solver", "map_path", "num_agents",
                     "num_humans", "horizon", "replan_every",
                     "fov_radius", "safety_radius"):
            cells *= len(sweep[axis])
        total += cells * len(seeds)
    return total


def main() -> None:
    yaml_text = build_yaml()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(yaml_text)
    print(f"wrote {OUT_PATH} ({len(yaml_text):,} bytes)")

    expected = (
        len(SOLVERS) * len(MAPS) * len(AGENT_COUNTS) * len(SEEDS)
    )
    total = verify(yaml_text)
    print(f"groups: {len(SOLVERS) * len(MAPS)}")
    print(f"cell count (re-parsed): {total}")
    print(f"expected:               {expected}")
    if total != expected:
        raise SystemExit(f"FAIL: cell count {total} != {expected}")
    print("OK")


if __name__ == "__main__":
    main()
