"""Generate the §5.4 agent-scaling sweep YAML at (r_fov=3, r_safe=1).

Output: ``configs/tuning/scaling_agents_fov3_safe1.yaml`` — a
560-cell sweep (4 solvers × 2 maps × 7 num_agents × 10 seeds)
sweeping ``num_agents`` at fixed (fov=3, safe=1, horizon=40,
replan=20, num_humans=100).

This is one of four §5.4 scaling sweeps that supersede the older
``scaling_agents.yaml`` (6 solvers, placeholder fov/safe) and
``scaling_humans.yaml``.  The four sweeps split cleanly across
two clusters for parallel execution:

    Cluster 1:  scaling_agents_fov3_safe1 → scaling_agents_fov4_safe2
    Cluster 2:  scaling_humans_fov3_safe1 → scaling_humans_fov4_safe2

Hypothesis under test:
    POE-Solver's safety (Theorem 1) and throughput properties
    hold across 4 Tier-1 backends as agent density grows, at
    each of two fov/safe operating points.

Design notes:

* Single method (``ours``); ``global_solver`` axis varies the
  Tier-1 backend.  Tier-2 (buffer-aware controller) held constant.
* Solver list reduced from 6 to 4 (dropped cbsh2 and pbs after
  the §5.5 / horizon-tuning analysis showed them to be uniformly
  dominated on the warehouse maps).
* ``num_humans`` fixed at 100 to hold exogenous density constant.
* fov_radius and safety_radius are HARDCODED in this generator
  (not placeholders) — see the companion
  ``generate_scaling_agents_fov4_safe2_yaml.py`` for the other
  operating point.

Usage::

    python scripts/tuning/generate_scaling_agents_fov3_safe1_yaml.py

Reproducibility: identical constants → byte-identical YAML.
"""
from __future__ import annotations

from pathlib import Path
from typing import List

# Local-only import so we don't pollute ``scripts.tuning`` with a real
# package; the helper lives alongside this script.
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _sweep_config_common import (  # noqa: E402
    base_solver_budget_yaml,
    base_validity_guard_yaml,
    solver_provenance_comment,
)

# ---------------------------------------------------------------------------
# Sweep constants — single source of truth.
# ---------------------------------------------------------------------------

SOLVERS: List[str] = ["lacam_official", "lacam3", "lns2", "pibt2"]

MAPS: List[str] = [
    "data/maps/warehouse-10-20-10-2-2.map",
    "data/maps/random-64-64-10.map",
]

AGENT_COUNTS: List[int] = [25, 50, 75, 100, 150, 200, 250]
NUM_HUMANS: int = 100

HORIZON: int = 40
REPLAN_EVERY: int = 20
FOV_RADIUS: int = 3
SAFETY_RADIUS: int = 1

SEEDS: List[int] = list(range(10))

OUT_PATH = Path(__file__).resolve().parent.parent.parent \
    / "configs" / "tuning" / "scaling_agents_fov3_safe1.yaml"


def _map_tag(map_path: str) -> str:
    return Path(map_path).stem.replace("-", "_")


def _header() -> str:
    return (
        "# Auto-generated by scripts/tuning/generate_scaling_agents_fov3_safe1_yaml.py.\n"
        "# DO NOT edit by hand; rerun the generator to regenerate.\n"
        "#\n"
        "# §5.4 agent-scaling sweep at (r_fov=3, r_safe=1).\n"
        "#\n"
        "#   4 solvers × 2 maps × 7 num_agents × 10 seeds = 560 runs.\n"
        "#\n"
        "# One of four §5.4 scaling sweeps; companions:\n"
        "#   scaling_agents_fov4_safe2.yaml\n"
        "#   scaling_humans_fov3_safe1.yaml\n"
        "#   scaling_humans_fov4_safe2.yaml\n"
        "# Together they supersede the older 6-solver scaling_agents.yaml\n"
        "# and scaling_humans.yaml.\n"
        "#\n"
        + solver_provenance_comment(SOLVERS) +
        "\n"
        "name: scaling_agents_fov3_safe1\n"
        "description: |\n"
        "  §5.4 agent-scaling sweep at (r_fov=3, r_safe=1).\n"
        "  560 runs: 4 solvers × 2 maps × 7 num_agents × 10 seeds.\n"
        "  num_humans fixed at 100; horizon=40, replan_every=20.\n"
        "\n"
        "base:\n"
        "  mode: lifelong\n"
        "  steps: 2000\n"
        "  human_model: random_walk\n"
        "  map_to_human_model:\n"
        "    warehouse-10-20-10-2-1: aisle\n"
        "    warehouse-10-20-10-2-2: aisle\n"
        "    random-64-64-10: random_walk\n"
        "  local_planner: astar\n"
        "  task_allocator: congestion_avoidance\n"
        "  lambda_conflict: 0.5\n"
        "  max_rounds: 5\n"
        "  hard_safety: true\n"
        "  communication_mode: priority\n"
        + base_solver_budget_yaml()
        + base_validity_guard_yaml() +
        "  log_violations_timeline: true\n"
        "\n"
        "seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n"
        "\n"
        "groups:\n"
    )


def _group_yaml(solver: str, map_path: str) -> str:
    map_tag = _map_tag(map_path)
    agent_counts_inline = "[" + ", ".join(str(n) for n in AGENT_COUNTS) + "]"
    return (
        f"  # ----- {solver} on {map_tag} -----\n"
        f"  - name: {solver}_{map_tag}\n"
        f"    sweep:\n"
        f"      method:        [ours]\n"
        f"      global_solver: [{solver}]\n"
        f"      map_path:      [{map_path}]\n"
        f"      num_agents:    {agent_counts_inline}\n"
        f"      num_humans:    [{NUM_HUMANS}]\n"
        f"      horizon:       [{HORIZON}]\n"
        f"      replan_every:  [{REPLAN_EVERY}]\n"
        f"      fov_radius:    [{FOV_RADIUS}]\n"
        f"      safety_radius: [{SAFETY_RADIUS}]\n"
    )


def build_yaml() -> str:
    parts = [_header()]
    for solver in SOLVERS:
        for map_path in MAPS:
            parts.append(_group_yaml(solver, map_path))
    return "".join(parts)


def verify(yaml_text: str) -> int:
    import yaml
    spec = yaml.safe_load(yaml_text)
    total = 0
    for g in spec["groups"]:
        cells = 1
        for v in g["sweep"].values():
            cells *= len(v)
        total += cells * len(spec["seeds"])
    return total


def main() -> None:
    yaml_text = build_yaml()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(yaml_text)
    print(f"wrote {OUT_PATH} ({len(yaml_text):,} bytes)")
    expected = len(SOLVERS) * len(MAPS) * len(AGENT_COUNTS) * len(SEEDS)
    total = verify(yaml_text)
    print(f"groups: {len(SOLVERS) * len(MAPS)}")
    print(f"cell count (re-parsed): {total}")
    print(f"expected:               {expected}")
    if total != expected:
        raise SystemExit(f"FAIL: cell count {total} != {expected}")
    print("OK")


if __name__ == "__main__":
    main()
