"""Generate the §5.6 deadlock / wait-time decomposition sweep YAML.

Output: ``configs/tuning/deadlock_wait.yaml`` — a 270-cell sweep
(3 methods × 9 agent counts × 10 seeds) on warehouse-10-20-10-2-2
at fixed exogenous density (X=100).

Hypothesis under test (§5.6):
    POE-Solver's deadlock + wait-time decomposition characterizes
    favorably vs the two rigid-follower baselines (pibt2_fr,
    lacam_blind) as controlled-agent density grows.

Design notes:

* 3 methods: ours, pibt2_fr, lacam_blind.  RHCR is deferred (see
  docs/RHCR_DEFERRED.md) — lacam_blind is the §5.5 / §5.8 substitute
  preserving the rigid-follower comparison at LaCAM Tier-1 quality.
* One sweep group per method.  Inside each group the inner sweep
  varies num_agents over the 9 M values.  This keeps the YAML
  self-documenting per method.
* Hyperparameters for method=ours are set explicitly in the shared
  base section (horizon=40, replan_every=20, fov=4, safe=1,
  task_allocator=congestion_avoidance, lambda_conflict=0.5,
  max_rounds=5).  The pibt2_fr and lacam_blind factories override
  their solver/controller fields at dispatch time
  (run_paper_experiment.py:_apply_method); the YAML does not need
  per-method overrides for those fields.
* log_violations_timeline: true so the §5.6 figures can plot the
  per-tick agent_attr / exo_attr curves alongside the deadlock /
  wait-decomposition metrics.

Cell count:
    3 methods × 9 num_agents × 10 seeds = 270.

The new ``Metrics.max_global_no_progress_streak`` and
``Metrics.global_no_progress_steps`` fields (commit eae3758) ride
the standard CSV pipeline; both appear as columns in results.csv
without any harness change.

Usage::

    python scripts/tuning/generate_deadlock_wait_yaml.py

Reproducibility: identical constants → byte-identical YAML.
"""
from __future__ import annotations

from pathlib import Path
from typing import List

# Local-only import so we don't pollute ``scripts.tuning`` with a real
# package; the helper lives alongside this script.
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _sweep_config_common import (  # noqa: E402
    base_solver_budget_yaml,
    base_validity_guard_yaml,
    solver_provenance_comment,
)

# ---------------------------------------------------------------------------
# Sweep constants — single source of truth.
# ---------------------------------------------------------------------------

METHODS: List[str] = ["ours", "pibt2_fr", "lacam_blind"]

M_VALUES: List[int] = [50, 100, 150, 200, 250, 300, 350, 400, 450]
NUM_HUMANS: int = 100

MAP_PATH: str = "data/maps/warehouse-10-20-10-2-2.map"

# Operating point for method=ours.  pibt2_fr / lacam_blind factories
# override these where applicable (e.g., pibt2_fr forces horizon=20,
# replan_every=1, controller_kind=global_only at dispatch time).
HORIZON: int = 40
REPLAN_EVERY: int = 20
FOV_RADIUS: int = 4
SAFETY_RADIUS: int = 1
GLOBAL_SOLVER: str = "lacam_official"

SEEDS: List[int] = list(range(10))

OUT_PATH = Path(__file__).resolve().parent.parent.parent \
    / "configs" / "tuning" / "deadlock_wait.yaml"


def _map_tag(map_path: str) -> str:
    return Path(map_path).stem.replace("-", "_")


def _header() -> str:
    return (
        "# Auto-generated by scripts/tuning/generate_deadlock_wait_yaml.py.\n"
        "# DO NOT edit by hand; rerun the generator to regenerate.\n"
        "#\n"
        "# §5.6 deadlock and wait-time decomposition sweep.\n"
        "#\n"
        "#   3 methods × 9 num_agents × 10 seeds = 270 runs.\n"
        "#\n"
        "# Methods: ours, pibt2_fr, lacam_blind.  RHCR deferred —\n"
        "# see docs/RHCR_DEFERRED.md; lacam_blind is the §5.5 / §5.8\n"
        "# substitute preserving the rigid-follower comparison at\n"
        "# LaCAM Tier-1 quality.\n"
        "#\n"
        "# Map: warehouse-10-20-10-2-2.  num_humans fixed at 100.\n"
        "# Operating point (method=ours):\n"
        "#   horizon=40, replan_every=20, fov=4, safe=1,\n"
        "#   task_allocator=congestion_avoidance (lambda=0.5, max_rounds=5).\n"
        "# pibt2_fr / lacam_blind use their own factory configs at\n"
        "# dispatch time; the YAML does not override their solver /\n"
        "# controller fields.\n"
        "#\n"
        + solver_provenance_comment([GLOBAL_SOLVER])
        + "\n"
        "name: deadlock_wait\n"
        "description: |\n"
        "  §5.6 deadlock and wait-time decomposition across 3 methods on\n"
        "  warehouse-10-20-10-2-2 at fixed |X|=100, varying |M| from 50\n"
        "  to 450.  270 cells total.\n"
        "\n"
        "base:\n"
        "  mode: lifelong\n"
        "  steps: 2000\n"
        "  human_model: random_walk\n"
        "  map_to_human_model:\n"
        "    warehouse-10-20-10-2-1: aisle\n"
        "    warehouse-10-20-10-2-2: aisle\n"
        "    random-64-64-10: random_walk\n"
        f"  global_solver: {GLOBAL_SOLVER}\n"
        f"  horizon: {HORIZON}\n"
        f"  replan_every: {REPLAN_EVERY}\n"
        f"  fov_radius: {FOV_RADIUS}\n"
        f"  safety_radius: {SAFETY_RADIUS}\n"
        "  hard_safety: true\n"
        "  communication_mode: priority\n"
        "  local_planner: astar\n"
        "  task_allocator: congestion_avoidance\n"
        "  lambda_conflict: 0.5\n"
        "  max_rounds: 5\n"
        + base_solver_budget_yaml()
        +         "  log_violations_timeline: true\n"
        "\n"
        + base_validity_guard_yaml()
        + "\n"
        "seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n"
        "\n"
        "groups:\n"
    )


def _group_yaml(method: str) -> str:
    """Emit a single sweep group for one method.  Inner sweep
    varies num_agents over M_VALUES."""
    map_tag = _map_tag(MAP_PATH)
    m_inline = "[" + ", ".join(str(n) for n in M_VALUES) + "]"
    return (
        f"  # ----- {method} on {map_tag} -----\n"
        f"  - name: {method}_{map_tag}\n"
        f"    sweep:\n"
        f"      method:      [{method}]\n"
        f"      map_path:    [{MAP_PATH}]\n"
        f"      num_agents:  {m_inline}\n"
        f"      num_humans:  [{NUM_HUMANS}]\n"
    )


def build_yaml() -> str:
    parts = [_header()]
    for method in METHODS:
        parts.append(_group_yaml(method))
    return "".join(parts)


def verify(yaml_text: str) -> int:
    import yaml
    spec = yaml.safe_load(yaml_text)
    total = 0
    for g in spec["groups"]:
        cells = 1
        for v in g["sweep"].values():
            cells *= len(v)
        total += cells * len(spec["seeds"])
    return total


def main() -> None:
    yaml_text = build_yaml()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(yaml_text)
    print(f"wrote {OUT_PATH} ({len(yaml_text):,} bytes)")
    expected = len(METHODS) * len(M_VALUES) * len(SEEDS)
    total = verify(yaml_text)
    print(f"groups: {len(METHODS)}")
    print(f"cell count (re-parsed): {total}")
    print(f"expected:               {expected}")
    if total != expected:
        raise SystemExit(f"FAIL: cell count {total} != {expected}")
    print("OK")


if __name__ == "__main__":
    main()
